const API_BASE = process.env.NEXT_PUBLIC_API_BASE ?? process.env.API_BASE ?? "http://localhost:4000";

async function getData() {
  try {
    const res = await fetch(`${API_BASE}/v1/control-tower`, { cache: "no-store" });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export default async function DailyOpsPrintPage() {
  const data = await getData();
  if (!data) return <div className="print-page"><h1>Failed to load data</h1></div>;

  return (
    <div className="print-page" style={{ fontFamily: "monospace", padding: 24, maxWidth: 800 }}>
      <h1 style={{ borderBottom: "2px solid #000", paddingBottom: 8, marginBottom: 16 }}>Daily Operations Summary</h1>
      <p style={{ color: "#666", marginBottom: 24 }}>{new Date().toLocaleDateString()} | Overall Health: {data.overallHealthScore}/100</p>

      <h2>Today</h2>
      <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 24 }}>
        <tbody>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Meals Due</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.today.mealsDue}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Meals Served</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.today.mealsServed} ({data.today.mealCompletionPct}%)</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Batches Due</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.today.batchesDue}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Active Batches</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.today.batchesActive}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Blocked Batches</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right", fontWeight: data.today.batchesBlocked > 0 ? 700 : 400 }}>{data.today.batchesBlocked}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Shortages</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right", fontWeight: data.today.shortageCount > 0 ? 700 : 400 }}>{data.today.shortageCount}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Expiring Lots</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.today.expiringLotCount}</td></tr>
        </tbody>
      </table>

      {data.attentionQueue.length > 0 && (
        <>
          <h2>Attention Queue</h2>
          <ol style={{ marginBottom: 24 }}>
            {data.attentionQueue.map((item: { id: string; severity: string; title: string; description: string }) => (
              <li key={item.id} style={{ marginBottom: 8 }}>
                <strong>[{item.severity.toUpperCase()}]</strong> {item.title} — {item.description}
              </li>
            ))}
          </ol>
        </>
      )}

      <h2>Scores</h2>
      <table style={{ width: "100%", borderCollapse: "collapse" }}>
        <tbody>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Data Quality</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.scientificQa.dataQualityScore}/100</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Client Readiness</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.clientData.readinessScore}/100</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>System Health</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.reliability.healthScore}/100</td></tr>
        </tbody>
      </table>

      <p style={{ marginTop: 32, color: "#999", fontSize: "0.85em" }}>Generated by Numen Ops Control Tower</p>
    </div>
  );
}
