const API_BASE = process.env.NEXT_PUBLIC_API_BASE ?? process.env.API_BASE ?? "http://localhost:4000";

async function getData() {
  try {
    const res = await fetch(`${API_BASE}/v1/control-tower`, { cache: "no-store" });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export default async function QaSummaryPrintPage() {
  const data = await getData();
  if (!data) return <div className="print-page"><h1>Failed to load data</h1></div>;

  return (
    <div className="print-page" style={{ fontFamily: "monospace", padding: 24, maxWidth: 800 }}>
      <h1 style={{ borderBottom: "2px solid #000", paddingBottom: 8, marginBottom: 16 }}>Scientific QA Summary</h1>
      <p style={{ color: "#666", marginBottom: 24 }}>{new Date().toLocaleDateString()} | Data Quality Score: {data.scientificQa.dataQualityScore}/100</p>

      <h2>Verification Tasks</h2>
      <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 24 }}>
        <tbody>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Open Tasks</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.scientificQa.openVerificationTasks}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Critical/High</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right", fontWeight: data.scientificQa.criticalVerificationTasks > 0 ? 700 : 400 }}>{data.scientificQa.criticalVerificationTasks}</td></tr>
        </tbody>
      </table>

      <h2>Quality Control</h2>
      <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 24 }}>
        <tbody>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Open QC Issues</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.scientificQa.openQcIssues}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Pending Calibration Reviews</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.scientificQa.pendingCalibrationReviews}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Pending Substitutions</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.scientificQa.pendingSubstitutions}</td></tr>
        </tbody>
      </table>

      <h2>Client Data</h2>
      <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 24 }}>
        <tbody>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Stale Biometrics</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.clientData.staleBiometrics}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Unverified Documents</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.clientData.unverifiedDocs}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Failed Parsing</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.clientData.failedParsing}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Client Readiness Score</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.clientData.readinessScore}/100</td></tr>
        </tbody>
      </table>

      <h2>System Reliability</h2>
      <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 24 }}>
        <tbody>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Failed Imports</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.reliability.failedImports}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>Stuck Batches</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.reliability.stuckBatches}</td></tr>
          <tr><td style={{ padding: 4, borderBottom: "1px solid #ddd" }}>System Health Score</td><td style={{ padding: 4, borderBottom: "1px solid #ddd", textAlign: "right" }}>{data.reliability.healthScore}/100</td></tr>
        </tbody>
      </table>

      <p style={{ marginTop: 32, color: "#999", fontSize: "0.85em" }}>Generated by Numen Scientific QA Module</p>
    </div>
  );
}
